plugin: amazon.aws.aws_ec2
regions:
  - eu-west-1
hostnames:
  - instance-id
filters:
  tag:userEnv: non-prod
  tag:userService: jenkins
compose:
  ansible_aws_ssm_region: placement.region
  ansible_connection: '"community.aws.aws_ssm"'
  ansible_host: instance_id
  ansible_aws_ssm_bucket_name: '"<s3_bucket_name>"'
groups:
  # Using true as the filter is already defined in the filters section so this will always match
  jenkins-dev: tags.Name in ["jenkins-dev"]