plugin: amazon.aws.aws_ec2
regions:
  - eu-west-1
hostnames:
  - instance-id
filters:
  tag:userEnv: non-prod
  tag:userService: mongodb
compose:
  ansible_aws_ssm_region: placement.region
  ansible_connection: '"community.aws.aws_ssm"'
  ansible_host: instance_id
  ansible_aws_ssm_bucket_name: '"<s3_bucket_name>"'
groups:
  mongodb-non-prod: tags.Name in ["mongodb-node-1", "mongodb-node-2"]